backend:
  branch: main
  name: github
  open_authoring: true
  repo: OCA/docs
  squash_merges: true
  use_graphql: true

display_url: https://oca-docs.netlify.app
logo_url: https://odoo-community.org/web/image/2994125-3cbbb295/OCA%20-%20Logo%20Vertical%20Dark%20Tagline%20Full%20WordMark%40512.png
media_folder: static/media
public_folder: /media
publish_mode: editorial_workflow
site_url: https://oca-docs.netlify.app

collections:
  - name: page
    create: true
    label: Pages
    folder: content
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: module
    create: true
    label: Modules
    folder: content/module
    fields:
      - { label: "Technical name", name: "slug", widget: "string" }
      - { label: "Human-readable name", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Usage", name: "usage", widget: "markdown", required: false }
      - { label: "Context", name: "context", widget: "markdown", required: false }
      - { label: "Installation", name: "install", widget: "markdown", required: false }
      - label: "Configuration"
        name: "configure"
        widget: "markdown"
        required: false
